ViewModels/SongModeViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MusicApp.Models
{
    public class SongModeViewModel
    {
        public List<SongModel> Songs { get; set; }
        public string ChosenTitle { get; set; }
        public SongModeViewModel()
        {

        }
    }
}

Controllers/KeyboardModeController.cs
using MusicApp.Database;
using MusicApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MusicApp.Controllers
{
    public class KeyboardModeController : Controller
    {
        // GET: KeyboardMode
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult ChooseMode(KeyboardModeModel keyboardMode)
        {
            if (keyboardMode.Mode == "free")
                return View("~/Views/Keyboard/Index.cshtml");
            else if (keyboardMode.Mode == "exercise")
                return View("~/Views/KeyboardMode/ExerciseMode.cshtml");
            else if (keyboardMode.Mode == "song")
                return RedirectToAction("showSongs");
            else if (keyboardMode.Mode == "improvisation")
                return View("~/Views/KeyboarMode/Index.cshtml");
            else
                return View("~/Views/Keyboard/Index.cshtml");
        }


        public ActionResult showSongs() {
            SongModeViewModel songViewModel = new SongModeViewModel();
            songViewModel.Songs = MongoDatabaseConnection.getSongs();

            return View("~/Views/KeyboardMode/SongMode.cshtml",songViewModel);
        }

        [HttpPost]
        public ActionResult LoadSong(SongModeViewModel songViewModel)
        {
            SongModel song = MongoDatabaseConnection.getSong(songViewModel.ChosenTitle);
            return View("~/Views/Keyboard/Index.cshtml", song);
        }


    }
}

Views/KeyboardMode/Index.cshtml
@model MusicApp.Models.KeyboardModeModel

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <div> 
        @using (Html.BeginForm("ChooseMode", "KeyboardMode", FormMethod.Post))
        {
            <div class="bs-example" style="border:2px solid gray;">

                <div class="form-group centerlook">
                    <h1> Choose mode </h1>
                </div>
                <div class="form-group centerlook">
                    <label>Free</label>
                    @Html.RadioButtonFor(m => m.Mode, "free")
                    <label>Excercise</label>
                    @Html.RadioButtonFor(m => m.Mode, "exercise")
                    <label>Song</label>
                    @Html.RadioButtonFor(m => m.Mode, "song")
                    <label>Improvisation</label>
                    @Html.RadioButtonFor(m => m.Mode, "improvisation")

                </div>
              
                <div class="">

                    <input type="submit" value="Login" class="btn btn-primary" />

                </div>
            </div>
        }
    </div>
</body>
</html>

Views/KeyboardMode/SongMode.cshtml
@model MusicApp.Models.SongModeViewModel

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>View</title>
</head>
<body>
    <div> 
        @using (Html.BeginForm("LoadSong", "KeyboardMode", FormMethod.Post))
        {
                foreach (var song in Model.Songs)
                {
                    <label>@Html.RadioButtonFor(model => model.ChosenTitle, song.title) @song.title</label>
                    <br />
                }
            <input type="submit" value="Login" class="btn btn-primary" />
        }
    </div>
</body>
</html>