ViewModels/SongAssignmentViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MusicApp.Models
{
    public class SongAssignmentViewModel
    {
        public List<SongAssingnmentModel> SongAssignments { get; set; }
        public List<UserModel> Users { get; set; }
        public List<SongDetailsModel> SongsDetails { get; set; }
        public string ChosenStudent { get; set; }
        public List<SongAssignmentDisplay> SongAssignmentsDisplay { get; set; }

    }



}

Controllers/SongAssignmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MusicApp.Database;
using MusicApp.Models;

namespace MusicApp.Controllers
{
    public class SongAssignmentController : Controller
    {
        // GET: SongAssignment
        public ActionResult Index()
        {
            SongAssignmentViewModel songAssignmentVM = new SongAssignmentViewModel();
            songAssignmentVM.SongsDetails = SqlDatabaseConnection.getSongsDetails();
            songAssignmentVM.Users = SqlDatabaseConnection.getStudents();

            return View(songAssignmentVM);
        }

        [HttpPost]
        public ActionResult DisplayAssignments(SongAssignmentViewModel songAssignmentVM)
        {

            //TO DO!
            songAssignmentVM = new SongAssignmentViewModel();
            songAssignmentVM.SongsDetails = SqlDatabaseConnection.getSongsDetails();
            songAssignmentVM.Users = SqlDatabaseConnection.getStudents();
            songAssignmentVM.SongAssignments = SqlDatabaseConnection.getSongAssignments();

            string chosenStudent = songAssignmentVM.ChosenStudent;
            string[] fullName;
            string firstName = null;
            string lastName = null;
            //if (string.IsNullOrEmpty(chosenStudent))
            //{
            //     fullName = chosenStudent.Split();
            //     firstName = fullName[0];
            //     lastName = fullName[1];
            //}





            //int chosenStudentId = int.Parse(songAssignmentVM.Users
            //    .Where(user => user.FirstName == firstName && user.LastName == lastName)
            //    .Select(user => user.Id)
            //    .ToList().FirstOrDefault().ToString());

            int chosenStudentId = 2;

            List<SongAssingnmentModel> assignmentsToDisplay = songAssignmentVM.SongAssignments
                .Where(a => a.UserId == chosenStudentId)
                .Select(a => a)
                .ToList();

            List<SongDetailsModel> detailsToDisplay = new List<SongDetailsModel>();
            foreach(var assignment in assignmentsToDisplay)
            {
                detailsToDisplay.Add(songAssignmentVM.SongsDetails
                    .Where(det => det.Id == assignment.SongDetailsId)
                    .Select(a => a)
                    .ToList().First());
            }

            List<SongAssignmentDisplay> result = new List<SongAssignmentDisplay>();

            if(assignmentsToDisplay.Count == detailsToDisplay.Count)
            {
                for(int i =0; i< assignmentsToDisplay.Count; i++)
                {
                    result.Add(new SongAssignmentDisplay()
                    {
                        Title = detailsToDisplay[i].Title,
                        Author = detailsToDisplay[i].Author,
                        OrginalTempo = detailsToDisplay[i].OrginalTempo,
                        StartTempo = assignmentsToDisplay[i].StartTempo,
                        DestinationTempo = assignmentsToDisplay[i].DestinationTempo
                    });
                }
            }
            songAssignmentVM.SongAssignmentsDisplay = result;

            return View("~/Views/SongAssignment/Index.cshtml",songAssignmentVM);
        }
    }
}

Views/SongAssignment/Index.cshtml
@model MusicApp.Models.SongAssignmentViewModel

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <div> 
        <table>
            <tr>
                <th> Imię </th>
                <th> Nazwisko </th>
            </tr>
            @foreach (var user in Model.Users)
            {
                <tr>@user.FirstName @user.LastName</tr>}
        </table>
       
        <table>
            <tr>
                <th> Tytuł </th>
                <th> Autor </th>
                <th> Tempo</th>
            </tr>
            @foreach (var song in Model.SongsDetails)
            {
                <tr>
                    <td> @song.Title</td>
                    <td> @song.Author</td>
                    <td> @song.OrginalTempo</td>
                </tr>
            }
           
            
        </table>
    </div>
    <p>Dodajemy</p>
    <div class="form-control">
        @using (Html.BeginForm("DisplayAssignments", "SongAssignment", FormMethod.Post,Model))
        {
            @Html.DropDownListFor(m=>m.ChosenStudent, new SelectList(Model.Users.Select(user => user.FirstName + " " + user.LastName).ToList()), null, new { @class = "form-control" });
            <input type="submit" value="Show Assignments" class="btn btn-primary" />
        }
    </div>
    <div>
        @if ( Model.SongAssignmentsDisplay != null)
        {
            <table>
                <tr>
                    <th> Tytuł </th>
                    <th> Autor </th>
                    <th> Oryginalne Tempo</th>
                    <th> Startowe Tempo</th>
                    <th> Zadane Tempo</th>
                </tr>
                @foreach (var songAssign in Model.SongAssignmentsDisplay)
                {
                    <tr>
                        <td> @songAssign.Author</td>
                        <td> @songAssign.Title</td>
                        <td> @songAssign.OrginalTempo</td>
                        <td> @songAssign.StartTempo</td>
                        <td> @songAssign.DestinationTempo</td>
                       
                    </tr>
                }
                </table>
        }
</div>
</body>
</html>